export const PasswordsFolderList = [
  {
    id: "1",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022393/loadpasswordfolder_ii5i7s.png",
    title: "Loan Account Password",
    bg: "#FFBE9D1A",
    navigate: "loan-account",
  },
  {
    id: "2",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022345/nonbankpassword_kjnhdb.png",
    title: "Password (Non Banker)",
    bg: "#F19ECE1A",
    navigate: "non-bank-account",
  },
  {
    id: "3",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022345/creditcardpasswordfolder_dxuk2c.png",
    title: "Creditcard Password",
    bg: "#1877F21A",
    navigate: "credit-card",
  },
  {
    id: "4",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022345/miscpasswordfolder_kxhoa7.png",
    title: "Misc Form",
    bg: "#F878661A",
    navigate: "misc-account",
  },
  {
    id: "5",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022345/bankaccpasswordfolder_gmax5r.png",
    title: "Bank Account Password",
    bg: "#F878661A",
    navigate: "bank-account",
  },
  {
    id: "6",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022345/merchantaccfolder_f1lrud.png",
    title: "Merchant Account",
    bg: "#FFBE9D1A",
    navigate: "merchant-account",
  },
  {
    id: "7",
    icon: "https://res.cloudinary.com/dlsxq98fr/image/upload/v1687022345/receipsfolder_jd41uz.png",
    title: "Recipes",
    bg: "#F19ECE1A",
    navigate: "recipe",
  },
];
